# stylua.toml

indent_type = "Spaces"     # 使用空格缩进
indent_width = 4           # 缩进宽度为 2
column_width = 100         # 每行最大列宽
line_endings = "Unix"      # 换行风格（Unix）
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Always"
no_call_parentheses = false
